### ISSUE TITLE
Uncaught TypeError: Cannot read property 'all' of undefined

### ISSUE THREAD

**Issue by RealMG** [elegantchaos/atom-ide-swift#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: [ide-swift](https://github.com/elegantchaos/atom-ide-swift) package 0.1.8

### Stack Trace

Uncaught TypeError: Cannot read property 'all' of undefined

```
At /home/nico/.atom/packages/ide-swift/lib/targets-view.js:22

TypeError: Cannot read property 'all' of undefined
    at /packages/ide-swift/lib/targets-view.js:22:43)
    at IdeSwiftController.chooseTarget (/packages/ide-swift/lib/ide-swift-controller.js:267:22)
    at HTMLElement.ideSwiftTarget (/packages/ide-swift/lib/ide-swift-controller.js:156:44)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:130:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:109:12)
```

### Commands

```
  2x -1:47 ide-swift:target (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-swift 0.1.8 
language-swift-89 0.4.0 
tool-bar 1.1.10 
```

**Comment by RealMG** [comment]
Fix it, I did not install the packages correctly,.

if you update the atom to a newer version, you might need to reinstall some packages.
